version: '3.8'

services:
  db:
    image: postgres:16
    container_name: pabellones_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Seb@0811
      POSTGRES_DB: pabellones_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
