services:
  db:
    image: postgres:16
    container_name: pabellones_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pabellones_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pabellones_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/pabellones_db"
    volumes:
      - .:/app

volumes:
  postgres_data:
